###########################
# PseudoAPI Bungee Config #
###########################

# DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 1

########################
# Server Configuration #
########################

# List of server names and player-friendly names to display
ServerList:
  main: "Main"
  skyblock: "Skyblock"

################
# Data Storage #
################

# Data backend configuration
Backend: mysql

# Define backends here:
Backends:
  mysql:
    type: mysql
    host: 127.0.0.1
    port: 3306
    username: username
    password: password
    database: PseudoPlugins
    prefix: "Pseudo_"
    useSSL: true
    verifyServerCertificate: false
    requireSSL: false


#####################################
# Join/Leave/Server Change Messages #
#####################################

# Enable custom join/leave/server change messages
EnableJoinLeave: true

# Join message format
# {name} = Full player name
# {nickname} = Player Nickname (If present, otherwise the full name will be used)
# {uuid} = Player UUID
# Color Codes Enabled
# Leave empty for no message
JoinFormat: "&e{nickname} &ejoined the network"

# Leave message format
# {name} = Full player name
# {nickname} = Player Nickname (If present, otherwise the full name will be used)
# {uuid} = Player UUID
# Color Codes Enabled
# Leave empty for no message
LeaveFormat: "&e{nickname} &eleft the network"

# Leave message format
# {name} = Full player name
# {nickname} = Player Nickname (If present, otherwise the full name will be used)
# {uuid} = Player UUID
# {server} = Name of server player has moved to
# {server_nick} = Friendly nickname of server player has moved to
# {last_server} = Name of server player was last connected to
# {last_server_nick} = Friendly nickname of server player was last connected to
# Color Codes Enabled
# Leave empty for no message
ServerChangeFormat: "&e{nickname} &ehas moved to &c{server_nick}"


###########
# Updater #
###########

# Should the server check for updates on startup?
StartupUpdate: true

# How long should the server wait after startup to check updates? (in seconds)
StartupDelay: 60

# How often should update checks occur (in minutes)
# Set to 0 to disable
UpdateFrequency: 60

# Should updates be downloaded when found?
DownloadUpdates: true

# Should the server restart upon downloading plugins?
UpdateRestart: true

# Should the server wait to restart until the server is empty?
RestartEmpty: true

# How long should the server wait to restart after warning players? (in seconds)
RestartWarning: 60