###########################
# PseudoAPI Bukkit Config #
###########################

# DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 10

###########
# Plugins #
###########

# Hide plugins from players?
HidePlugins: true

# Allow players to see PseudoAPI plugins?
ShowPseudoAPI: true

# Default server locale
DefaultLocale: en-us


################
# Data Storage #
################

# Data backend configuration for global data
GlobalBackend: globalfile

# Data backend configuration for this server
ServerBackend: file

# Server and global backends must be different!
# It is recommended to use the same database, but different prefixes if only 1 database is available.

# Define backends here:
Backends:
  file:
    type: file
    # Relative to plugin directory if not absolute
    directory: Data
  globalfile:
    type: file
    directory: GlobalData
  mysql:
    type: mysql
    host: 127.0.0.1
    port: 3306
    username: username
    password: password
    database: PseudoPlugins
    prefix: "Pseudo_"
    useSSL: true
    verifyServerCertificate: false
    requireSSL: false


############################
# BungeeCord Configuration #
############################

# Is server on BungeeCord network?
BungeeEnabled: false


########
# Chat #
########

# Separate each color code by a comma, either color names can be used, or color codes with or without '&' or 'ยง'

# Plugin Info Border Color
BorderColor: DARK_AQUA

# Plugin Info Title Color
TitleColor: GOLD

# Help Command Color
CommandColor: RED

# Help Description Color
DescriptionColor: AQUA

# Message Text Color
TextColor: GREEN

# Error Text Color
ErrorTextColor: RED

# Plugin Prefix Color
PluginPrefixColor: BLUE,BOLD

# Plugin Error Prefix Color
PluginErrorPrefixColor: BLUE,BOLD

# Plugin Message Format
# {name} = Full Plugin Name
# {nickname} = Plugin Nickname (If present, otherwise the full name will be used)
# {player} = Player Name
# {playernick} = Player Nickname
# {message} = Message
MessageFormat: "{nickname}> {message}"

# Plugin Error Message Format
# {name} = Full Plugin Name
# {nickname} = Plugin Nickname (If present, otherwise the full name will be used)
# {player} = Player Name
# {playernick} = Player Nickname
# {message} = Message
ErrorMessageFormat: "{nickname}> {message}"

# Click Command Event
# Suggest or Run
ClickEvent: run

# Console Format
# Is newest console message at top or bottom?
# Usually top for Multicraft, but bottom for standard terminals
ConsoleFormat: bottom


###########
# Updater #
###########

# Should the server check for updates on startup?
StartupUpdate: true

# How long should the server wait after startup to check updates? (in seconds)
StartupDelay: 60

# How often should update checks occur (in minutes)
# Set to 0 to disable
UpdateFrequency: 720

# Should updates be downloaded when found?
DownloadUpdates: true

# Should the server restart upon downloading plugins?
UpdateRestart: true

# Should the server wait to restart until the server is empty?
RestartEmpty: true

# How long should the server wait to restart after warning players? (in seconds)
RestartWarning: 60