#########################
#PseudoAPI Bukkit Config#
#########################

#DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 8

#########
#Plugins#
#########

#Hide plugins from players?
HidePlugins: true

#Allow players to see PseudoAPI plugins?
AllowPseudoAPI: true


##############
#Data Storage#
##############

#Data backend configuration
Backend: file

#Define backends here:
Backends:
  file:
    type: file
    #Relative to plugin directory if not absolute
    directory: Data
  mysql:
    type: mysql
    host: 127.0.0.1
    port: 3306
    username: username
    password: password
    database: PseudoPlugins
    prefix: "Pseudo_"
    useSSL: true


##########################
#BungeeCord Configuration#
##########################

#Is server on BungeeCord network?
BungeeEnabled: false


######
#Chat#
######

#Plugin Info Border Color
BorderColor: DARK_AQUA

#Plugin Info Title Color
TitleColor: GOLD

#Help Command Color
CommandColor: RED

#Help Description Color
DescriptionColor: AQUA

#Message Text Color
TextColor: GREEN

#Message Prefix Color
PrefixColor: BLUE,BOLD

#Error Text Color
ErrorColor: RED

#Error Prefix Color
ErrorPrefixColor: BLUE,BOLD

#Plugin Message Format
#{name} = Plugin Formal Name
#{nickname} = Plugin Nickname (If Present, Otherwise Formal)
#{player} = Player Name
#{playernick} = Player Nickname
#{message} = Message
#Color Codes Enabled
MessageFormat: "{nickname}> {message}"

#Click Command Event
#Suggest or Run Command
ClickEvent: Run

#Console Format
#Is newest console message at top or bottom?
#Usually top for Multicraft and bottom for self-hosted servers
ConsoleFormat: bottom

#Time Format
#Use following codes:
#https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
TimeFormat: "HH:mm:ss"

#Date Format
#Use following codes:
#https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
DateFormat: "yyyy-MM-dd"

#How frequently TPS is checked for
#In ticks, how often the plugin will calculate the current TPS
TPSUpdateFrequency: 40