name: ${project.artifactId}
author: PseudoResonance
main: io.github.pseudoresonance.pseudoapi.bukkit.PseudoAPI
version: ${revision}
description: An API for Easy Access to Resources
api-version: 1.13
commands:
  pseudoapi:
    description: PseudoAPI Menu
  plugins:
    description: Plugins
    permission: pseudoapi.plugins
  pl:
    description: Plugins
    permission: pseudoapi.plugins
  allplugins:
    description: All plugins
    permission: pseudoapi.allplugins
    aliases: [allpl]
permissions:
  pseudoapi.update:
    description: Allows the player to update plugins
    default: op
  pseudoapi.update.notify:
    description: Allows the player to get update notifications
    default: op
  pseudoapi.backend:
    description: Allows the player to configure backends
    default: op
  pseudoapi.plugins:
    description: Allows the player to see PseudoAPI plugins
    default: true
  pseudoapi.allplugins:
    description: Allows the player to see all plugins
    default: op
    children:
      pseudoapi.plugins: true
  pseudoapi.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudoapi.reset:
    description: Allows the player to reset the plugin
    default: op
    children:
      pseudoapi.reload: true
  pseudoapi.reloadlocalization:
    description: Allows the player to reload the plugin localization
    default: op
  pseudoapi.resetlocalization:
    description: Allows the player to reset the plugin localization
    default: op
    children:
      pseudoapi.reloadlocalization: true
  pseudoapi.setlocalization:
    description: Allows the player to set their localization
    default: true
  pseudoapi.setlocalization.others:
    description: Allows the player to set the localization of other players
    default: op
    children:
      pseudoapi.setlocalization: true
  pseudoapi.*:
    description: Gives the user all PseudoAPI permissions
    default: op
    children:
      pseudoapi.plugins: true
      pseudoapi.allplugins: true
      pseudoapi.backend: true
      pseudoapi.reset: true
      pseudoapi.resetlocalization: true
      pseudoapi.setlocalization.others: true
      pseudoapi.update: true
      pseudoapi.update.notify: true