name: PseudoAPI
author: PseudoResonance
main: io.github.pseudoresonance.pseudoapi.bukkit.PseudoAPI
version: 3.2.1
description: An API for Easy Access to Resources
commands:
  pseudoapi:
    description: PseudoAPI Menu
  plugins:
    description: Plugins
    permission: pseudoapi.plugins
  pl:
    description: Plugins
    permission: pseudoapi.plugins
  allplugins:
    description: All plugins
    permission: pseudoapi.allplugins
    aliases: [allpl]
permissions:
  pseudoapi.update:
    description: Allows the player to update plugins
    default: op
  pseudoapi.backend:
    description: Allows the player to configure backends
    default: op
  pseudoapi.plugins:
    description: Allows the player to see PseudoAPI plugins
    default: true
  pseudoapi.allplugins:
    description: Allows the player to see all plugins
    default: op
    children:
      pseudoapi.plugins: true
  pseudoapi.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudoapi.reset:
    description: Allows the player to reset the plugin
    default: op
  pseudoapi.*:
    description: Gives the user all PseudoAPI permissions
    default: op
    children:
      pseudoapi.plugins: true
      pseudoapi.allplugins: true
      pseudoapi.backend: true
      pseudoapi.reload: true
      pseudoapi.reset: true
      pseudoapi.update: true