name: PseudoAPI
author: PseudoResonance
main: io.github.pseudoresonance.pseudoapi.bukkit.PseudoAPI
version: 3.1.2
description: An API for Easy Access to Resources
commands:
  pseudoapi:
    description: PseudoAPI Menu
  plugins:
    description: Plugins
    permission: pseudoapi.plugins
  pl:
    description: Plugins
    permission: pseudoapi.plugins
  allplugins:
    description: All plugins
    permission: pseudoapi.allplugins
    aliases: [allpl]
  metrics:
    description: System metrics
    permission: pseudoapi.metrics
    aliases: [lag,tps]
  brand:
    description: Player client brand
    permission: pseudoapi.brand
permissions:
  pseudoapi.backend:
    description: Allows the player to configure backends
    default: op
  pseudoapi.brand:
    description: Allows the player to see user's client brands
    default: op
  pseudoapi.metrics:
    description: Allows the player to see detailed system metrics
    default: op
    children:
      pseudoapi.metrics.tps: true
  pseudoapi.metrics.tps:
    description: Allows the player to see tps details in system metrics
    default: op
  pseudoapi.metrics.java:
    description: Allows the player to see java details in system metrics
    default: op
  pseudoapi.metrics.cpu:
    description: Allows the player to see cpu details in system metrics
    default: op
  pseudoapi.metrics.memory:
    description: Allows the player to see memory details in system metrics
    default: op
  pseudoapi.plugins:
    description: Allows the player to see PseudoAPI plugins
    default: true
  pseudoapi.allplugins:
    description: Allows the player to see all plugins
    default: op
    children:
      pseudoapi.plugins: true
  pseudoapi.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudoapi.reset:
    description: Allows the player to reset the plugin
    default: op
  pseudoapi.*:
    description: Gives the user all PseudoAPI permissions
    default: op
    children:
      pseudoapi.plugins: true
      pseudoapi.allplugins: true
      pseudoapi.backend: true
      pseudoapi.brand: true
      pseudoapi.metrics: true
      pseudoapi.metrics.java: true
      pseudoapi.metrics.cpu: true
      pseudoapi.metrics.memory: true
      pseudoapi.reload: true
      pseudoapi.reset: true