name: WolfAPI
author: WolfLeader116
main: io.github.wolfleader116.wolfapi.bukkit.WolfAPI
version: 2.1
description: An API for Easy Access to Resources
commands:
  wolfapi:
    description: WolfAPI Menu
  plugins:
    description: Plugins
    permission: wolfapi.plugins
  pl:
    description: Plugins
    permission: wolfapi.plugins
  allplugins:
    description: All plugins
    permission: wolfapi.allplugins
    aliases: [allpl]
permissions:
  wolfapi.plugins:
    description: Allows the player to see WolfAPI plugins
    default: true
  wolfapi.allplugins:
    description: Allows the player to see all plugins
    default: op
    children:
      wolfapi.plugins: true
  wolfapi.reload:
    description: Allows the player to reload the plugin
    default: op
  wolfapi.reset:
    description: Allows the player to reset the plugin
    default: op
  wolfapi.*:
    description: Gives the user all WolfAPI permissions
    default: op
    children:
      wolfapi.plugins: true
      wolfapi.allplugins: true
      wolfapi.reload: true
      wolfapi.reset: true